#!/usr/bin/env bash

rt="/ptv"
hrt="${rt}/healer"
source ${rt}/rtsetup.sh

cd ${hrt}/healerenum/subenum/

# Pass all the arguments to the dnsbrute tool
dnsbrute $@ -r ${hrt}/healerenum/subenum/resolvers.txt -w ${hrt}/healerenum/subenum/sublist.txt
