#!/usr/bin/env bash

rt="/ptv"
hrt="${rt}/healer"
source ${rt}/rtsetup.sh

# If we have and argument "--httpx" in arguments list
if [[ " ${@} " =~ " --httpx " ]]; then
    # set run_httpx to 1
    run_httpx=1
fi

function help() {
echo -e "a_subfinder - Finds all subdomains of a domain by automating the subfinder tool.

Usage:
\ta_subfinder <domain>
"
}

# Check if subfinder is installed
if ! command -v subfinder &> /dev/null
then
    seterror "subfinder could not be found"
fi

# Run subfinder against a domain
function run_subfinder() {
    domain=$1
    # echo -e "Running subfinder against ${domain}..."
    subfinder -d ${domain} -silent
    # echo -e "Done."
}

run_subfinder $1